/* autogenerated by Processing revision 1301 on 2025-04-30 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.io.*;
import java.net.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class proc extends PApplet {

PPlot p = new PPlot();
float scale = 3;
boolean auto = false;
int ms;

public void setup() {
  /* size commented out by preprocessor */;
  surface.setTitle("Plotter");
  surface.setResizable(true);
  background(255);
}

public void draw() {
  telnet_tick();
  p.redraw(0, 0, width, height, scale, false);
  
  if (auto && millis() - ms > 60) {
    ms = millis();
    p.move();
  }
}

public void telnet_data(String data) {
  p.parse(data);
  ms = millis();
}

public void mouseWheel(MouseEvent e) {
  scale -= e.getCount() / 5.0f;
  scale = max(scale, 0.05f);
}

public void mousePressed() {
  auto = !auto;
}
class LBUF {
  public void resize(int nsize) {
    if (buf == null) {
      buf = new float[nsize];
    } else {
      if (buf.length == nsize) return;
      if (nsize > buf.length) {
        float[] nbuf = new float[nsize];
        System.arraycopy(buf, 0, nbuf, 0, buf.length);
        buf = nbuf;
      } else {
        if (length > nsize) length = nsize;
      }
    }
  }

  public void add(float val) {
    if (buf == null) resize(1);
    System.arraycopy(buf, 0, buf, 1, min(buf.length - 1, length));
    if (length < buf.length) ++length;
    buf[0] = val;
  }

  public float get(int i) {
    return buf[i];
  }

  public float[] buf = null;
  public int length = 0;
};

class PPlot {
  // парсить данные:
  // - числа, разделённые ';' или ',' - значения осей
  // - текст, разделённый ';' или ',' - подписи осей
  // - текст, начинающийся с '#' - заголовок графика
  public void parse(String str) {
    if (str.startsWith("#")) {
      _title = str.substring(1);
      _upd = true;
      return;
    }

    String[] s = str.split(";|,");
    if (s.length == 0) return;

    char c = s[0].charAt(0);
    if (Character.isDigit(c) || c == '-') {
      float[] arr = new float[s.length];
      for (int i = 0; i < s.length; i++) {
        arr[i] = parseFloat(s[i].trim());
      }
      add(arr);
    } else {
      lbls = s;
    }
    _upd = true;
  }

  // добавить данные напрямую
  public void add(float[] data) {
    if (buf == null || buf.length != data.length) {
      buf = new LBUF[data.length];
      for (int i = 0; i < buf.length; i++) {
        buf[i] = new LBUF();
      }
      if (lbls == null || lbls.length != data.length) {
        lbls = new String[data.length];
        for (int i = 0; i < data.length; i++) {
          lbls[i] = "Line " + i;
        }
      }
    }
    for (int i = 0; i < data.length; i++) {
      buf[i].add(data[i]);
    }
    _upd = true;
  }

  // сдвинуть график на 1 единицу
  public void move() {
    if (buf == null) return;
    float[] arr = new float[buf.length];
    for (int i = 0; i < buf.length; i++) {
      arr[i] = buf[i].get(0);
    }
    add(arr);
  }

  // обновить график
  public void redraw(int x, int y, int w, int h, float scale) {
    redraw(x, y, w, h, scale, true);
  }
  public void redraw(int x, int y, int w, int h, float scale, boolean show) {
    if (buf == null || buf.length == 0 || buf[0].length == 0) return;

    boolean resize = _x != x || _y != y || _w != w || _h != h;
    if (resize) p = createGraphics(w, h);
    if (resize || _s != scale || _upd) {
      _x = x;
      _y = y;
      _w = w;
      _h = h;
      _s = scale;
      _upd = false;
      show = true;

      for (LBUF b : buf) b.resize(round(w / scale));

      int offyt = 20;
      int offyb = 7;
      int offx = 2;
      int tgap = 10;
      int huestep = 151;

      //p = createGraphics(w, h);
      p.beginDraw();

      // window
      p.noStroke();
      p.fill(255);
      p.rect(0, 0, w, h, 3);
      p.colorMode(HSB, 255, 255, 255);

      y = offyt;
      x = offx;
      h -= offyb + offyt;
      w -= offx * 2;

      // minmax
      int maxv = 999999999;
      float max = -maxv, min = maxv;
      for (int i = 0; i < buf[0].length; i++) {
        for (LBUF b : buf) {
          if (b.get(i) > max) max = b.get(i);
          if (b.get(i) < min) min = b.get(i);
        }
      }

      // labels
      if (lbls != null) {
        p.noStroke();
        p.textSize(15);
        p.textAlign(LEFT, BASELINE);
        float lw = 0;
        float tw[] = new float[lbls.length];
        for (int i = 0; i < lbls.length; i++) {
          tw[i] = p.textWidth(lbls[i]);
          lw += tw[i] + tgap;
        }
        int xx = w - (int)lw + tgap;
        for (int i = 0; i < lbls.length; i++) {
          p.fill((i * huestep) % 255, 255, 200);
          p.text(lbls[i], xx, y - 5);
          xx += tw[i] + tgap;
        }
      }

      // title
      if (_title.length() > 0) {
        p.fill(0);
        p.textAlign(CENTER, BASELINE);
        p.text(_title, x + w / 2, y - 5);
      }

      // grid
      int am = round(h / 80);
      float dif = max - min;
      float step = dif / am;
      p.textSize(13);
      p.textAlign(LEFT, BASELINE);
      p.fill(0);
      for (int i = 0; i < am + 1; i++) {
        float v = max - step * i;
        float yy = (min == max) ? (y + h) / 2 : map(max - step * i, min, max, y + h, y);
        p.strokeWeight(0.3f);
        p.stroke(100);
        p.line(x, yy, x + w, yy);

        p.noStroke();
        p.text(v, 5, yy - 3);
      }

      // lines
      p.strokeWeight(1.5f);

      for (int b = 0; b < buf.length; b++) {
        p.stroke((b * huestep) % 255, 255, 200);

        float px = 0, py = 0;
        for (int i = 0; i < buf[b].length; i++) {
          float xx = x + w - i * scale;
          float yy = (min == max) ? (y + h) / 2 : map(buf[b].get(i), min, max, y + h, y);
          if (xx < x) {
            p.line(px, py, x, yy);
            break;
          }
          if (i > 0) p.line(px, py, xx, yy);
          px = xx;
          py = yy;
        }
      }

      p.endDraw();
    }
    if (show) image(p, _x, _y);
  }

  PGraphics p;
  LBUF[] buf = null;
  String[] lbls = null;
  String _title = "";
  int _x = 0, _y = 0, _w = 0, _h = 0;
  float _s = 0;
  boolean _upd = false;
};



Socket socket;
BufferedReader reader;
PrintWriter writer;
boolean started = false;

public void telnet_start() {
  try {
    socket = new Socket("localhost", 4000);
    reader = new BufferedReader(new InputStreamReader(socket.getInputStream()));
    writer = new PrintWriter(socket.getOutputStream(), true);
    started = true;

    println("Connected to the Telnet server");
  }
  catch (IOException e) {
    e.printStackTrace();
    println("Failed to connect to the Telnet server");
    delay(1000);
  }
}

public void telnet_tick() {
  if (started) {
    try {
      if (reader.ready()) telnet_data(reader.readLine());
    }
    catch (IOException e) {
      e.printStackTrace();
    }
  } else {
    telnet_start();
  }
}

public void telnet_send(String data) {
  writer.println(data);
}

public void telnet_stop() {
  try {
    if (reader != null) reader.close();
    if (writer != null) writer.close();
    if (socket != null) socket.close();
    println("Disconnected from the Telnet server");
  }
  catch (IOException e) {
    e.printStackTrace();
  }
}


  public void settings() { size(800, 300); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "proc" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
